spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cs425final
    username: postgres
    password: 987321
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true